baseURL = "https://example.org/"
languageCode = "zh-cn"
title = "示例博客"
theme = "bolo"

[params]
  avatar = "https://zhangzhuo-1257627961.cos.ap-beijing.myqcloud.com/boke/boke4.jpg"
  hitokoto = "生活不止眼前的代码，还有诗和远方。"
  
  [[params.social]]
    name = "GitHub"
    url = "https://github.com"
    icon = "solo-github"
  
  [[params.links]]
    name = "GitHub"
    url = "https://github.com"
    desc = "全球最大的代码托管平台"
  
  [[params.links]]
    name = "MDN Web Docs"
    url = "https://developer.mozilla.org"
    desc = "Mozilla开发者文档，Web开发权威指南"
  
  [[params.links]]
    name = "Stack Overflow"
    url = "https://stackoverflow.com"
    desc = "全球最大的程序员问答社区"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
    [menu.main.params]
      icon = "solo-home"
  
  [[menu.main]]
    name = "友情链接"
    url = "/links/"
    weight = 2
    [menu.main.params]
      icon = "solo-about"
  
  [[menu.main]]
    name = "时间线"
    url = "/archives/"
    weight = 3
    [menu.main.params]
      icon = "solo-list"

[taxonomies]
  tag = "tags"
  category = "categories"

[pagination]
  pagerSize = 10

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
